#include "scad/scad_export.h"
#include "core/string_builder.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* -------------------------------------------------------------------------
 * Companion library content
 * ---------------------------------------------------------------------- */
static const char LIBRARY_CONTENT[] =
    "// duncad_bezier.scad — DunCAD Bezier Companion Library\n"
    "// Arbitrary-degree De Casteljau evaluation for OpenSCAD.\n"
    "\n"
    "function dc_lerp(a, b, t) = a * (1 - t) + b * t;\n"
    "\n"
    "function dc_decasteljau(pts, t) =\n"
    "    len(pts) == 1 ? pts[0] :\n"
    "    dc_decasteljau([for (i = [0:len(pts)-2]) dc_lerp(pts[i], pts[i+1], t)], t);\n"
    "\n"
    "function dc_bezier_span(pts, steps) =\n"
    "    [for (i = [0:steps]) dc_decasteljau(pts, i / steps)];\n"
    "\n"
    "function dc_bezier_path(spans, steps) =\n"
    "    [for (span = spans) each dc_bezier_span(span, steps)];\n";

/* -------------------------------------------------------------------------
 * dc_scad_generate_library
 * ---------------------------------------------------------------------- */
char *
dc_scad_generate_library(void)
{
    char *result = malloc(sizeof(LIBRARY_CONTENT));
    if (!result) return NULL;
    memcpy(result, LIBRARY_CONTENT, sizeof(LIBRARY_CONTENT));
    return result;
}

/* -------------------------------------------------------------------------
 * dc_scad_generate_inline — self-contained SCAD with embedded library
 * ---------------------------------------------------------------------- */
char *
dc_scad_generate_inline(const char *name, const DC_ScadSpan *spans,
                        int num_spans, int closed, double thickness,
                        DC_Error *err)
{
    if (!name || !spans || num_spans <= 0) {
        if (err)
            DC_SET_ERROR(err, DC_ERROR_INVALID_ARG,
                         "scad_generate_inline: name, spans, and num_spans required");
        return NULL;
    }

    DC_StringBuilder *sb = dc_sb_new();
    if (!sb) {
        if (err)
            DC_SET_ERROR(err, DC_ERROR_MEMORY,
                         "scad_generate_inline: alloc failed");
        return NULL;
    }

    /* Header */
    dc_sb_append(sb, "// Generated by DunCAD — self-contained bezier module\n\n");

    /* Embedded bezier math (scoped with underscored names to avoid conflicts) */
    dc_sb_appendf(sb,
        "/* --- Bezier math for %s --- */\n"
        "function _%s_lerp(a, b, t) = a * (1 - t) + b * t;\n"
        "function _%s_decasteljau(pts, t) =\n"
        "    len(pts) == 1 ? pts[0] :\n"
        "    _%s_decasteljau(\n"
        "        [for (i = [0:len(pts)-2]) _%s_lerp(pts[i], pts[i+1], t)], t);\n"
        "function _%s_span(pts, steps) =\n"
        "    [for (i = [0:steps]) _%s_decasteljau(pts, i / steps)];\n"
        "function _%s_path(spans, steps) =\n"
        "    [for (span = spans) each _%s_span(span, steps)];\n\n",
        name, name, name, name, name, name, name, name, name);

    /* Spans array */
    dc_sb_appendf(sb, "%s_spans = [\n", name);
    for (int s = 0; s < num_spans; s++) {
        const DC_ScadSpan *span = &spans[s];
        dc_sb_append(sb, "    [");
        for (int p = 0; p < span->count; p++) {
            if (p > 0) dc_sb_append(sb, ", ");
            dc_sb_appendf(sb, "[%.4f, %.4f]",
                          span->points[p].x, span->points[p].y);
        }
        dc_sb_append(sb, "],\n");
    }
    dc_sb_append(sb, "];\n\n");

    /* 2D module */
    if (closed) {
        dc_sb_appendf(sb,
            "module %s_2d() {\n"
            "    polygon(_%s_path(%s_spans, 100));\n"
            "}\n\n",
            name, name, name);
    } else {
        /* Open curve: hull-chain circles along path for proper stroke width */
        double t = thickness > 0.0 ? thickness : 1.0;
        dc_sb_appendf(sb,
            "module %s_2d(width = %.4f) {\n"
            "    pts = _%s_path(%s_spans, 100);\n"
            "    for (i = [0:len(pts)-2])\n"
            "        hull() {\n"
            "            translate(pts[i])   circle(d = width);\n"
            "            translate(pts[i+1]) circle(d = width);\n"
            "        }\n"
            "}\n\n",
            name, t, name, name);
    }

    /* 3D modules */
    dc_sb_appendf(sb,
        "module %s(height = 5) {\n"
        "    linear_extrude(height = height)\n"
        "        %s_2d();\n"
        "}\n\n",
        name, name);

    dc_sb_appendf(sb,
        "module %s_revolve(angle = 360) {\n"
        "    rotate_extrude(angle = angle)\n"
        "        %s_2d();\n"
        "}\n\n",
        name, name);

    dc_sb_appendf(sb,
        "module %s_offset(r = 1) {\n"
        "    offset(r = r)\n"
        "        %s_2d();\n"
        "}\n\n",
        name, name);

    /* Preview call */
    dc_sb_appendf(sb, "%s();\n", name);

    char *result = dc_sb_take(sb);
    dc_sb_free(sb);

    if (!result && err)
        DC_SET_ERROR(err, DC_ERROR_MEMORY,
                     "scad_generate_inline: sb_take failed");

    return result;
}

/* -------------------------------------------------------------------------
 * dc_scad_generate
 * ---------------------------------------------------------------------- */
char *
dc_scad_generate(const char *name, const DC_ScadSpan *spans,
                 int num_spans, int closed, DC_Error *err)
{
    if (!name || !spans || num_spans <= 0) {
        if (err)
            DC_SET_ERROR(err, DC_ERROR_INVALID_ARG,
                         "scad_generate: name, spans, and num_spans required");
        return NULL;
    }

    DC_StringBuilder *sb = dc_sb_new();
    if (!sb) {
        if (err)
            DC_SET_ERROR(err, DC_ERROR_MEMORY, "scad_generate: alloc failed");
        return NULL;
    }

    /* Header */
    dc_sb_append(sb, "use <duncad_bezier.scad>\n");
    dc_sb_append(sb, "// Generated by DunCAD\n\n");

    /* Spans array */
    dc_sb_appendf(sb, "%s_spans = [\n", name);
    for (int s = 0; s < num_spans; s++) {
        const DC_ScadSpan *span = &spans[s];
        dc_sb_append(sb, "    [");
        for (int p = 0; p < span->count; p++) {
            if (p > 0) dc_sb_append(sb, ", ");
            dc_sb_appendf(sb, "[%.6f, %.6f]",
                          span->points[p].x, span->points[p].y);
        }
        dc_sb_append(sb, "],\n");
    }
    dc_sb_append(sb, "];\n\n");

    /* 2D module */
    if (closed) {
        dc_sb_appendf(sb,
            "module %s_2d() { polygon(dc_bezier_path(%s_spans, 100)); }\n",
            name, name);
    } else {
        dc_sb_appendf(sb,
            "module %s_2d() {\n"
            "    pts = dc_bezier_path(%s_spans, 100);\n"
            "    for (i = [0:len(pts)-2])\n"
            "        hull() { translate(pts[i]) circle(0.01); "
            "translate(pts[i+1]) circle(0.01); }\n"
            "}\n",
            name, name);
    }

    /* 3D module */
    dc_sb_appendf(sb,
        "module %s(height = 5) { linear_extrude(height) %s_2d(); }\n\n",
        name, name);

    /* Preview call */
    dc_sb_appendf(sb, "%s();\n", name);

    char *result = dc_sb_take(sb);
    dc_sb_free(sb);

    if (!result && err)
        DC_SET_ERROR(err, DC_ERROR_MEMORY, "scad_generate: sb_take failed");

    return result;
}

/* -------------------------------------------------------------------------
 * dc_scad_export
 * ---------------------------------------------------------------------- */
int
dc_scad_export(const char *path, const char *name,
               const DC_ScadSpan *spans, int num_spans,
               int closed, DC_Error *err)
{
    if (!path) {
        if (err)
            DC_SET_ERROR(err, DC_ERROR_INVALID_ARG,
                         "scad_export: path required");
        return -1;
    }

    /* Generate shape source */
    char *shape_src = dc_scad_generate(name, spans, num_spans, closed, err);
    if (!shape_src) return -1;

    /* Generate library source */
    char *lib_src = dc_scad_generate_library();
    if (!lib_src) {
        free(shape_src);
        if (err)
            DC_SET_ERROR(err, DC_ERROR_MEMORY,
                         "scad_export: library alloc failed");
        return -1;
    }

    /* Write shape file */
    FILE *f = fopen(path, "w");
    if (!f) {
        free(shape_src);
        free(lib_src);
        if (err)
            DC_SET_ERROR(err, DC_ERROR_IO,
                         "scad_export: cannot open %s", path);
        return -1;
    }
    fputs(shape_src, f);
    fclose(f);
    free(shape_src);

    /* Derive directory from path and build companion path */
    const char *slash = strrchr(path, '/');
    size_t dir_len = slash ? (size_t)(slash - path + 1) : 0;
    const char *lib_name = "duncad_bezier.scad";
    size_t lib_name_len = strlen(lib_name);

    /* "./duncad_bezier.scad" when no directory component */
    size_t prefix_len = dir_len > 0 ? dir_len : 2;
    char *lib_path = malloc(prefix_len + lib_name_len + 1);
    if (!lib_path) {
        free(lib_src);
        if (err)
            DC_SET_ERROR(err, DC_ERROR_MEMORY,
                         "scad_export: path alloc failed");
        return -1;
    }
    if (dir_len > 0) {
        memcpy(lib_path, path, dir_len);
        memcpy(lib_path + dir_len, lib_name, lib_name_len + 1);
    } else {
        memcpy(lib_path, "./", 2);
        memcpy(lib_path + 2, lib_name, lib_name_len + 1);
    }

    f = fopen(lib_path, "w");
    if (!f) {
        free(lib_src);
        if (err)
            DC_SET_ERROR(err, DC_ERROR_IO,
                         "scad_export: cannot open %s", lib_path);
        free(lib_path);
        return -1;
    }
    fputs(lib_src, f);
    fclose(f);
    free(lib_src);
    free(lib_path);

    return 0;
}

/* -------------------------------------------------------------------------
 * dc_scad_spans_free
 * ---------------------------------------------------------------------- */
void
dc_scad_spans_free(DC_ScadSpan *spans, int num_spans)
{
    if (!spans) return;
    for (int i = 0; i < num_spans; i++)
        free(spans[i].points);
    free(spans);
}
